#!/usr/bin/env ruby
# Extract global variable definitions from Project Zomboid Lua files
# This helps keep .luacheckrc in sync with actual PZ API

require 'set'

PZ_LUA_PATH = File.expand_path("~/Library/Application Support/Steam/steamapps/common/ProjectZomboid/Project Zomboid.app/Contents/Java/media/lua")

# Java-bridged globals that won't appear in Lua files
# These are provided by the PZ engine itself
MANUAL_GLOBALS = [
  # Java-side core API
  "Events",
  "Perks",
  "PerkFactory",
  "Recipe",
  "SkillBook",
  
  # Java functions
  "addXp",
  "getXp",
  "getPlayer",
  "getSpecificPlayer", 
  "getWorld",
  "getCell",
  "getCore",
  "getGameTime",
  "getSandboxOptions",
  "getServerOptions",
  "getScriptManager",
  "getAllRecipes",
  "getTexture",
  "getText",
  "getTextOrNull",
  "getTextManager",
  
  # Java utilities
  "instanceof",
  "isClient",
  "isServer",
  "isCoopHost",
  "isAdmin",
  "print",
  "luautils",
  "ZombRand",
  "ZombRandFloat",
  
  # Script system
  "ScriptManager",
  
  # UI / Fonts / Text
  "UIFont",
  "HaloTextHelper",
  
  # Character / Animations
  "CharacterActionAnims",
  "CharacterTrait",
  
  # Timed Actions
  "ISBaseTimedAction",
  "ISInventoryTransferAction",
  "HashMap",
  "Vector2",
  "IsoObject",
  "IsoGridSquare",
  "IsoPlayer",
  "IsoZombie",
  "IsoWorld",
  "InventoryItem",
  "ItemContainer",
  "Texture",
  "LuaEventManager",
  "triggerEvent",
  "getPlayerByOnlineID",
  "getOnlinePlayers",
  "ItemPickerJava",
  "ModOptions",
  "PZAPI",
]

unless Dir.exist?(PZ_LUA_PATH)
  puts "❌ PZ Lua path not found: #{PZ_LUA_PATH}"
  puts "Update PZ_LUA_PATH in this script to match your installation"
  exit 1
end

puts "📂 Scanning PZ Lua files in: #{PZ_LUA_PATH}"

globals = Set.new(MANUAL_GLOBALS)

# Scan for common global patterns
Dir.glob("#{PZ_LUA_PATH}/**/*.lua").each do |file|
  content = File.read(file)
  
  # Find global assignments (ClassName = ClassName or {})
  content.scan(/^([A-Z][A-Za-z0-9_]+)\s*=/) do |match|
    globals << match[0]
  end
  
  # Find global function definitions
  content.scan(/^function\s+([A-Za-z][A-Za-z0-9_]+)\s*\(/) do |match|
    globals << match[0]
  end
end

puts "\n📋 Found #{globals.size} total globals (#{MANUAL_GLOBALS.size} manual + #{globals.size - MANUAL_GLOBALS.size} extracted)"

# Output directly to .luacheckrc_globals.lua format
output = []
output << "-- Project Zomboid API globals"
output << "-- This file is included by .luacheckrc"
output << "-- Auto-generated by: ruby tools/extract_pz_globals.rb"
output << "-- Generated at: #{Time.now}"
output << ""
output << "return {"

# Manual globals first (in original order)
output << "    -- Manual/Java-side globals"
MANUAL_GLOBALS.each { |g| output << %Q(    "#{g}",) }
output << ""

# Then extracted globals, grouped by prefix
extracted = (globals - MANUAL_GLOBALS).to_a
grouped = extracted.group_by { |g| g[0..1] }
grouped.keys.sort.each do |prefix|
  items = grouped[prefix].sort
  output << "    -- #{prefix}* (auto-extracted)"
  items.each { |g| output << %Q(    "#{g}",) }
  output << ""
end

output << "}"

# Write to file or print
output_file = File.expand_path("../.luacheckrc_globals.lua", __dir__)
if ARGV.include?("--write")
  File.write(output_file, output.join("\n") + "\n")
  puts "✅ Wrote #{globals.size} globals to: #{output_file}"
  puts "   (#{MANUAL_GLOBALS.size} manual + #{extracted.size} auto-extracted)"
else
  puts "\n" + output.join("\n")
  puts "\n💡 To write directly to .luacheckrc_globals.lua:"
  puts "   ruby tools/extract_pz_globals.rb --write"
end
